Corrected Semantic Defintion of take(k)
sarveswaran-m/blockingMap4j pull request #4
Opened 2018-01-08 13:24 UTC by kuniss

I'm not sure whether I'm right here. But I assume, the deleted sentence is wrong here. 
If several consumers (threads) are waiting blocked by a take(k) for being satisfied and one of them wins when k is put in, then the other consumers should remain waiting, isn't it? Instead of returning null as the removed sentence is intending.
But as I said, I'm not sure what your initial intention was. In different context both may be meaningful.

May be it is worth to call a method covering you initial semantic (break blocking if another consumers wins) something like *takeAsWinner* or so.

2018-01-08 16:05 UTC, sarveswaran-m requested changes
Request you to refer to review comment and let me know what you think

2018-01-08 16:05 UTC, sarveswaran-m commented on README.md
> +    should be returned on only one of the threads and not on all the threads.
Checked current behaviour. All threads that await on a particular key would block [here](ap4j/blob/master/src/main/java/org/thavam/util/concurrent/blockingMap/ActiveBlockingHashMap.java#L374). Once the key becomes available, all threads would return with the awaited key and corresponding value. Hence, this point has to be updated to be consistent with current implementation.

But the above behaviour may not be right in a producer-consumer environment i.e we do not expect a job/product to be available to multiple consumers. Hence, only one thread should get the value/job. That behaviour is yet to be implemented. Should we create an issue to have such behaviour?

2018-01-08 17:37 UTC, kuniss commented on README.md
> +    should be returned on only one of the threads and not on all the threads.
You should also take into consideration backward compatibility. ... So, it may be better to create a new method (e.g. `takeAllOrNothing` or `takeAsWinner`; not sure what's better in English) which implements the new behavior. 
This is because both behaviors are meaningful under circumstances. If some one is using your library already he would not expect the actually semantic of `take(k)` being change so significantly...

But's your decision. You may make it clean first as in your initial intention and handle it as an issue.

2018-01-09 13:19 UTC, sarveswaran-m commented on README.md
> +    should be returned on only one of the threads and not on all the threads.
@kuniss I was wrong about the take behaviour. When multiple threads wait on the same key, only one gets the value when the key becomes available. Other threads return with null, indicating that the key became available but they did not get the value. This behaviour arises from the fact that the key and value are removed from primaryKeyMap when the key becomes available @ https://github.com/sarveswaran-m/blockingMap4j/blob/master/src/main/java/org/thavam/util/concurrent/blockingMap/ActiveBlockingHashMap.java#L380 I tested and verified this behaviour. The current description of take behaviour as given below correctly describes existing behaviour:

"If take(k) on a key that does not exist is invoked from multiple threads, all the thread should block till the key becomes available. When the key becomes available, all the blocked threads should be notified. Actual removal of the mapping can & should happen from only one of the threads. Therefore, the operation should be successful from only one thread. Hence, value should be returned on only one of the threads and not on all the threads. Null should be returned on threads on which the operation was not successful."

Hence, this description need not be changed.
Will be adding test case to capture this behaviour.

However, another way to convey that the operation did not succeed on a thread is to throw an exception instead of returning null. Am yet to decide whether that behaviour should also be brought in , perhaps on a different take method (eg: takeXXX). If the exception way to indicate take() failure on contention is to be built, that should be done in backward compatible manner as you have suggested.

2018-01-14 11:29 UTC, sarveswaran-m commented on README.md
> +    should be returned on only one of the threads and not on all the threads.
Added test case

2018-01-14 11:33 UTC, sarveswaran-m commented
Since take behaviour is consistent with documentation, closing this pull request for now.
Shall refine take behaviour after some consideration in future.

2018-01-14 11:33 UTC, closed without merging